// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wlmuwqhnevfumbefiqwy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndsbXV3cWhuZXZmdW1iZWZpcXd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NjA5MjQsImV4cCI6MjA3MTQzNjkyNH0.Qe-s-S_gxmawM2_NEbYm_3-QY2l47h6_M72WexzlPok";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});